
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "fullName": "IfedioraMMA chukwukadibe",
    "email": "his123@yahoo.com.com",
    "password": "123456",
    "role": "admin"
}


###
GET  http://localhost:3000/products

### 
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "email": "his123@yahoo.com.com",
    "password": "123456"
}

###
POST http://localhost:3000/brands
Content-Type: application/json 

{
    "brandName": "Gucci"
}

###
POST http://localhost:3000/products
Content-Type: application/json 



{
    "productName": "Beans",
      "cost": "200",
      "productImages": "http://fuclala.com",
      "description": "This is a loenght o noncsence",
      "stockStatus": "in-stock",
}

###
GET http://localhost:3000/products/DOLCE/1/2
